[project]
name = 'dependency-graphics'
version = "0.0.1"
dependencies = [
    'PyYAML ~= 6.0'
]
[project.optional-dependencies]
tests = [
    'assertpy ~= 1.1'
]
[build-system]
requires = ["setuptools", "assertpy"]
build-backend = "setuptools.build_meta"
