name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.12.1
              uses: actions/setup-python@v2
              with:
                python-version: 3.12.1
            - name: Execute Unit Tests
              run: |
                pip install --upgrade pip
                python3.10 -m venv env
                source env/bin/activate
                pip install .[tests]
                cd tests
                python -m pytest
            - name: Build
              run: |
                source env/bin/activate
                pip install -e .

